name: code-quality
on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  check-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: find src  -iname "*.h" -o -iname "*.cpp" | xargs clang-format-18 --dry-run --Werror

  check-clang-tidy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install libxerces-c-dev
      - run: cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/${{ matrix.compiler }}-test.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
      - run: cd ./build && make VERBOSE=1 -j5
      - run: clang-tidy-18 src/**/*.{cpp,h} -p ./build/compile_commands.json
