name: sanitizers

on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  build-asan:
    strategy:
      matrix:
        sanitizer:
          - asan
          - ubsan
        # - msan
        compiler:
          - gcc
          - clang
        build_type:
          - Debug
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install libxerces-c-dev
      - run: cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/${{ matrix.compiler }}-${{ matrix.sanitizer}}.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
      - run: cd ./build && make all VERBOSE=1
