name: sanitizers.yaml
on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  build-sanitized:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja -S $(pwd) -B $(pwd)/build
