name: sanitizers
on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  build-asan:
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        build_type:
          - Release
          - Debug
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install libxerces-c-dev
      - run: cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/${{ matrix.compiler }}-asan.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
      - run: cd ./build && make all
  build-ubsan:
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        build_type:
          - Release
          - Debug
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install libxerces-c-dev
      - run: cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/${{ matrix.compiler }}-ubsan.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
      - run: cd ./build && make all
