name: sanitizers
on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  build-sanitized:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=make -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
      - run: cd ./build && make all