name: run tests
run-name: run test
on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - gcc
    #          - clang
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install libxerces-c-dev
      - run: cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/${{ matrix.compiler }}-test.cmake  -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
      - run: cd $(pwd)/build && make all && ctest