name: run tests
run-name: run test
on:
  pull_request:
    branches:
      - master
      - ws*
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install libxerces-c-dev
      - run: cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/test.cmake  -G 'Unix Makefiles' -S $(pwd) -B $(pwd)/build
